# Xcode
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11.0.11'
    jdkArchitectureOption: 'x86'
    jdkSourceOption: 'PreInstalled'
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
 
      
      echo Hello  
      echo step0
      npm install -g npm
      echo step1
      npm install titanium -g
      echo step2
      npm install -g n
      echo step3
      n 14
      echo step4
      npm install -g git://github.com/appcelerator/titanium.git
      echo step5
      ti sdk install 
      echo step6
      ti sdk select 10.1.1.GA
      echo step7
      ti build -p android -b