# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
 
      
      echo Hello  
      
      npm install -g titanium
      echo step1  
      titanium sdk install --branch 3_0_X --default
      echo step2
      npm install git://github.com/appcelerator/titanium.git -g
      echo step3
      ti create --import --no-services
 