# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: 'macOS-latest'
  demands: xcode

 
steps:
- task: NodeTool@0
  displayName: 'Use Node 14.x'
  inputs:
    versionSpec: 14.19.3


- task: CmdLine@2
  inputs:
    script: |
    
      npm install -g npm
      echo step1
      npm install titanium -g
      echo step2
      npm install alloy -g
      npm install -g git://github.com/appcelerator/titanium.git
      echo step3
      ti sdk install
      ti sdk select 10.1.1.GA
      echo step 5
      ti build -p ios -b

 