# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  name: Default
  demands: xcode


steps:
- task: CmdLine@2
  inputs:
    script: |
 
      
      echo step0
      ti build --project-dir /Users/m1052070/Desktop/CartusMobile_Alloy_Mar2022 --platform android --target dist-playstore --android-sdk /Users/m1052070/Library/Android/sdk --output-dir /Users/m1052070/Desktop/output --keystore /Users/m1052070/Desktop/CartusKeystore.jks --alias cartusmobile --store-password 0X1D1ct10n
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'