# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
 
      
      echo Hello  
      
      npm install -g npm
      echo step1  
      npm install titanium -g
      echo step2
      npm install -g git://github.com/appcelerator/titanium.git
      echo step3  
      ti sdk install 
      echo step4  
      ti sdk select 10.1.1.GA