# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  name: Default
  demands: xcode


steps:
- task: CmdLine@2
  inputs:
    script: |
 
      
      echo step0
      xcodebuild -project /Users/m1052070/Desktop/KitchenSink/build/iphone/KitchenSink.xcodeproj -scheme KitchenSink -archivePath /Users/m1052070/Desktop/KitchenSink archive